/* ------------------------------------------------------------------
   The Fairmount Ledger — event listings
   ------------------------------------------------------------------ */

(function () {
  "use strict";

  // ---------- Data ----------
  //
  // Events + category map are loaded from js/events-data.js, which is
  // regenerated by the scrapers in /scraper. If that file is missing or
  // empty we fall back to an empty listing rather than erroring.
  var CATEGORIES = window.CATEGORIES || {};
  var EVENTS = Array.isArray(window.EVENTS) ? window.EVENTS : [];

  // ---------- State ----------

  var state = {
    view: "list",           // "list" | "calendar"
    filter: null,           // category key or null for all
    calYear: null,
    calMonth: null          // 0-indexed
  };

  var today = new Date();
  today.setHours(0, 0, 0, 0);
  state.calYear = today.getFullYear();
  state.calMonth = today.getMonth();

  // ---------- Helpers ----------

  function parseDate(str) {
    var p = str.split("-");
    return new Date(+p[0], +p[1] - 1, +p[2]);
  }

  function formatTime(hhmm) {
    var p = hhmm.split(":");
    var h = +p[0], m = p[1];
    var suffix = h >= 12 ? "p.m." : "a.m.";
    var h12 = h % 12 === 0 ? 12 : h % 12;
    return m === "00" ? h12 + " " + suffix : h12 + ":" + m + " " + suffix;
  }

  function shortTime(hhmm) {
    var p = hhmm.split(":");
    var h = +p[0], m = p[1];
    var h12 = h % 12 === 0 ? 12 : h % 12;
    return h12 + (m === "00" ? "" : ":" + m) + (h >= 12 ? "p" : "a");
  }

  var WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
  var MONTHS = ["January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"];

  function formatDateHeading(d) {
    return WEEKDAYS[d.getDay()] + ", " + MONTHS[d.getMonth()] + " " + d.getDate();
  }

  function sameDay(a, b) {
    return a.getFullYear() === b.getFullYear() &&
           a.getMonth() === b.getMonth() &&
           a.getDate() === b.getDate();
  }

  function visibleEvents() {
    var list = EVENTS.slice();
    if (state.filter) {
      list = list.filter(function (e) { return e.category === state.filter; });
    }
    list.sort(function (a, b) {
      var k = (a.date + a.time).localeCompare(b.date + b.time);
      return k;
    });
    return list;
  }

  function el(tag, className, text) {
    var node = document.createElement(tag);
    if (className) node.className = className;
    if (text != null) node.textContent = text;
    return node;
  }

  // ---------- List view ----------

  function renderList() {
    var root = document.getElementById("list-view");
    root.innerHTML = "";

    // List view starts at today — never show anything earlier.
    var events = visibleEvents().filter(function (ev) {
      return parseDate(ev.date) >= today;
    });
    document.getElementById("event-count").textContent =
      events.length + " listing" + (events.length === 1 ? "" : "s") +
      (state.filter ? " · " + CATEGORIES[state.filter] : "");

    if (!events.length) {
      root.appendChild(el("p", "list-empty", "Nothing coming up. Check back soon."));
      return;
    }

    var currentDate = null;
    var group = null;

    events.forEach(function (ev) {
      if (ev.date !== currentDate) {
        currentDate = ev.date;
        var d = parseDate(ev.date);

        group = el("div", "day-group");
        if (d < today) group.classList.add("is-past");

        var heading = el("div", "day-group__heading");
        heading.appendChild(el("h2", "day-group__date", formatDateHeading(d)));
        if (sameDay(d, today)) heading.appendChild(el("span", "day-group__badge", "Today"));
        group.appendChild(heading);
        root.appendChild(group);
      }

      var row = el("button", "event-row");
      row.type = "button";
      row.appendChild(el("span", "event-row__time", formatTime(ev.time)));

      var main = el("span", "event-row__main");
      main.appendChild(el("span", "event-row__title", ev.title));
      main.appendChild(el("br"));
      main.appendChild(el("span", "event-row__venue", ev.venue));
      row.appendChild(main);

      row.appendChild(el("span", "event-row__cat cat-" + ev.category, CATEGORIES[ev.category]));
      row.addEventListener("click", function () { openDetail(ev); });
      group.appendChild(row);
    });
  }

  // ---------- Calendar view ----------

  function renderCalendar() {
    var grid = document.getElementById("cal-grid");
    var monthLabel = document.getElementById("cal-month");
    grid.innerHTML = "";

    monthLabel.textContent = MONTHS[state.calMonth] + " " + state.calYear;

    var events = visibleEvents();
    var byDate = {};
    events.forEach(function (ev) {
      (byDate[ev.date] = byDate[ev.date] || []).push(ev);
    });

    document.getElementById("event-count").textContent =
      events.length + " listing" + (events.length === 1 ? "" : "s") +
      (state.filter ? " · " + CATEGORIES[state.filter] : "");

    var firstDay = new Date(state.calYear, state.calMonth, 1).getDay();
    var daysInMonth = new Date(state.calYear, state.calMonth + 1, 0).getDate();

    for (var i = 0; i < firstDay; i++) {
      grid.appendChild(el("div", "cal-cell cal-cell--empty"));
    }

    var MAX_SHOWN = 3;

    for (var day = 1; day <= daysInMonth; day++) {
      var key = state.calYear + "-" +
        String(state.calMonth + 1).padStart(2, "0") + "-" +
        String(day).padStart(2, "0");
      grid.appendChild(buildDayCell(new Date(state.calYear, state.calMonth, day),
                                    byDate[key] || [], MAX_SHOWN));
    }
  }

  // Build one calendar cell. A separate function so each day's click handlers
  // capture their own date/events (the render loop uses `var`).
  function buildDayCell(d, dayEvents, maxShown) {
    var cell = el("div", "cal-cell");
    if (sameDay(d, today)) cell.classList.add("cal-cell--today");
    cell.appendChild(el("div", "cal-cell__num", String(d.getDate())));

    dayEvents.slice(0, maxShown).forEach(function (ev) {
      var chip = el("button", "cal-event cat-" + ev.category);
      chip.type = "button";
      chip.title = ev.title + " — " + formatTime(ev.time);
      chip.appendChild(el("span", "cal-event__time", shortTime(ev.time)));
      chip.appendChild(el("span", "cal-event__title", ev.title));
      chip.addEventListener("click", function () { openDetail(ev); });
      cell.appendChild(chip);
    });

    if (dayEvents.length > maxShown) {
      var more = el("button", "cal-more", "+" + (dayEvents.length - maxShown) + " more");
      more.type = "button";
      more.addEventListener("click", function () { openDay(d, dayEvents); });
      cell.appendChild(more);
    }
    return cell;
  }

  function renderWeekdayHeader() {
    var row = document.getElementById("cal-weekdays");
    ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].forEach(function (name) {
      row.appendChild(el("div", "calendar__weekday", name));
    });
  }

  // ---------- Detail dialog ----------

  var overlay = document.getElementById("overlay");

  function openDetail(ev) {
    var d = parseDate(ev.date);
    var cat = document.getElementById("detail-category");
    cat.textContent = CATEGORIES[ev.category];
    cat.className = "detail__category cat-" + ev.category;

    document.getElementById("detail-title").textContent = ev.title;
    document.getElementById("detail-when").textContent =
      formatDateHeading(d) + " · " + formatTime(ev.time);
    document.getElementById("detail-venue").textContent = ev.venue;
    document.getElementById("detail-desc").textContent = ev.description || "";
    document.getElementById("detail-price").textContent = ev.price || "";

    var ticket = document.getElementById("detail-ticket");
    if (ev.url) {
      ticket.href = ev.url;
      ticket.hidden = false;
    } else {
      ticket.hidden = true;
    }

    overlay.hidden = false;
    document.getElementById("detail-close").focus();
  }

  function closeDetail() { overlay.hidden = true; }

  overlay.addEventListener("click", function (e) {
    if (e.target === overlay) closeDetail();
  });
  document.getElementById("detail-close").addEventListener("click", closeDetail);
  document.addEventListener("keydown", function (e) {
    if (e.key === "Escape" && !overlay.hidden) closeDetail();
  });

  // ---------- Day dialog (calendar "+N more") ----------

  var dayOverlay = document.getElementById("day-overlay");

  function openDay(d, dayEvents) {
    document.getElementById("day-title").textContent = formatDateHeading(d);
    var list = document.getElementById("day-list");
    list.innerHTML = "";
    dayEvents.forEach(function (ev) {
      var row = el("button", "day-row");
      row.type = "button";
      row.appendChild(el("span", "day-row__time", formatTime(ev.time)));
      var main = el("span", "day-row__main");
      main.appendChild(el("span", "day-row__title", ev.title));
      main.appendChild(el("span", "day-row__venue", ev.venue));
      row.appendChild(main);
      row.addEventListener("click", function () {
        closeDay();
        openDetail(ev);
      });
      list.appendChild(row);
    });
    dayOverlay.hidden = false;
    document.getElementById("day-close").focus();
  }

  function closeDay() { dayOverlay.hidden = true; }

  dayOverlay.addEventListener("click", function (e) {
    if (e.target === dayOverlay) closeDay();
  });
  document.getElementById("day-close").addEventListener("click", closeDay);
  document.addEventListener("keydown", function (e) {
    if (e.key === "Escape" && !dayOverlay.hidden) closeDay();
  });

  // ---------- Flyer venues (image-only schedules) ----------
  //
  // Some venues (e.g. Deano's Pub) publish their schedule only as a graphic.
  // Rather than OCR it, we show the flyer image itself in a dialog, opened from
  // a button per venue. Data comes from window.FLYERS (see js/events-data.js).

  var flyerOverlay = document.getElementById("flyer-overlay");
  var flyers = Array.isArray(window.FLYERS) ? window.FLYERS : [];

  function openFlyer(flyer) {
    document.getElementById("flyer-title").textContent = flyer.venue + " — this week's events";
    var img = document.getElementById("flyer-img");
    img.src = flyer.image || flyer.source;
    img.alt = flyer.venue + " events flyer";
    var src = document.getElementById("flyer-source");
    src.href = flyer.page || flyer.source;
    src.textContent = "View on " + (flyer.page || "").replace(/^https?:\/\//, "").replace(/\/$/, "") + " →";
    flyerOverlay.hidden = false;
    document.getElementById("flyer-close").focus();
  }

  function closeFlyer() { flyerOverlay.hidden = true; }

  flyerOverlay.addEventListener("click", function (e) {
    if (e.target === flyerOverlay) closeFlyer();
  });
  document.getElementById("flyer-close").addEventListener("click", closeFlyer);
  document.addEventListener("keydown", function (e) {
    if (e.key === "Escape" && !flyerOverlay.hidden) closeFlyer();
  });

  function renderFlyerButtons() {
    var wrap = document.getElementById("flyer-buttons");
    wrap.innerHTML = "";
    flyers.forEach(function (flyer) {
      if (!flyer.image && !flyer.source) return;
      var btn = el("button", "flyer-btn", flyer.venue);
      btn.type = "button";
      btn.title = "See " + flyer.venue + "'s weekly flyer";
      btn.addEventListener("click", function () { openFlyer(flyer); });
      wrap.appendChild(btn);
    });
  }

  // ---------- View switching & filters ----------

  var btnList = document.getElementById("btn-list");
  var btnCal = document.getElementById("btn-calendar");
  var listView = document.getElementById("list-view");
  var calView = document.getElementById("calendar-view");

  function setView(view) {
    state.view = view;
    var isList = view === "list";
    btnList.classList.toggle("is-active", isList);
    btnCal.classList.toggle("is-active", !isList);
    btnList.setAttribute("aria-selected", isList);
    btnCal.setAttribute("aria-selected", !isList);
    listView.hidden = !isList;
    calView.hidden = isList;
    render();
  }

  btnList.addEventListener("click", function () { setView("list"); });
  btnCal.addEventListener("click", function () { setView("calendar"); });

  document.getElementById("cal-prev").addEventListener("click", function () {
    state.calMonth--;
    if (state.calMonth < 0) { state.calMonth = 11; state.calYear--; }
    renderCalendar();
  });

  document.getElementById("cal-next").addEventListener("click", function () {
    state.calMonth++;
    if (state.calMonth > 11) { state.calMonth = 0; state.calYear++; }
    renderCalendar();
  });

  function renderFilters() {
    var wrap = document.getElementById("category-filters");
    wrap.innerHTML = "";

    var all = el("button", "filter-pill" + (state.filter === null ? " is-active" : ""), "All");
    all.type = "button";
    all.addEventListener("click", function () { state.filter = null; renderFilters(); render(); });
    wrap.appendChild(all);

    // Venue pills after "All", alphabetically by label (ignoring a leading "The").
    function sortKey(key) {
      return CATEGORIES[key].replace(/^the\s+/i, "").toLowerCase();
    }
    Object.keys(CATEGORIES).sort(function (a, b) {
      return sortKey(a).localeCompare(sortKey(b));
    }).forEach(function (key) {
      var pill = el("button", "filter-pill" + (state.filter === key ? " is-active" : ""), CATEGORIES[key]);
      pill.type = "button";
      pill.addEventListener("click", function () {
        state.filter = state.filter === key ? null : key;
        renderFilters();
        render();
      });
      wrap.appendChild(pill);
    });
  }

  function render() {
    if (state.view === "list") renderList();
    else renderCalendar();
  }

  // ---------- Init ----------

  renderWeekdayHeader();
  renderFilters();
  renderFlyerButtons();
  render();
})();
